{
  'auxiliary_data_hash': None,
  'certificates': None,
  'collateral': None,
  'collateral_return': None,
  'fee': 170000,
  'inputs': [
    {
      'index': 0,
      'transaction_id': TransactionId(hex='732bfd67e66be8e8288349fcaaa2294973ef6271cc189a239bb431275401b8e5'),
    },
  ],
  'mint': None,
  'network_id': None,
  'outputs': [
    {
      'address': addr_test1vrm9x2zsux7va6w892g38tvchnzahvcd9tykqf3ygnmwtaqyfg52x,
      'amount': {'coin': 100000000000, 'multi_asset': {}},
      'datum': None,
      'datum_hash': None,
      'post_alonzo': False,
      'script': None,
    },
    {
      'address': addr_test1vrm9x2zsux7va6w892g38tvchnzahvcd9tykqf3ygnmwtaqyfg52x,
      'amount': {'coin': 799999834103, 'multi_asset': {}},
      'datum': None,
      'datum_hash': None,
      'post_alonzo': False,
      'script': None,
    },
  ],
  'reference_inputs': None,
  'required_signers': None,
  'script_data_hash': None,
  'total_collateral': None,
  'ttl': None,
  'update': None,
  'validity_start': None,
  'withdraws': None,
}
